name: Plex Download Processing

on:
  repository_dispatch:
    types:
      - download_movie

jobs:
  process-download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Plex Manager Script
        env:
          INPUT_USER: ${{ github.event.client_payload.user }}
          INPUT_PASS_HASH: ${{ github.event.client_payload.pass_hash }}
          VALID_USER: ${{ secrets.APP_USER }}
          VALID_PASS: ${{ secrets.APP_PASSWORD }}
          C411_TOKEN: ${{ secrets.C411_API_TOKEN }}
          ALLDEBRID_KEY: ${{ secrets.ALLDEBRID_API_KEY }}
          MOVIE_TITLE: ${{ github.event.client_payload.title }}
          MOVIE_YEAR: ${{ github.event.client_payload.year }}
        run: |
          python process_download.py
