name: Process Movie Download

on:
  repository_dispatch:
    types: [download_movie]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Search & Send
        env:
          APP_USER: ${{ secrets.APP_USER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          C411_API_TOKEN: ${{ secrets.C411_API_TOKEN }}
          ALLDEBRID_API_KEY: ${{ secrets.ALLDEBRID_API_KEY }}
        run: |
          python process_download.py "${{ github.event.client_payload.title }}" "${{ github.event.client_payload.year }}" "${{ github.event.client_payload.user }}" "${{ github.event.client_payload.pass_hash }}"
